/*
 * JFrGothaStart.java
 */
package info.vannier.gotha;

import net.miginfocom.swing.MigLayout;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.net.InetAddress;
import java.rmi.RemoteException;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import ru.gofederation.gotha.util.GothaLocale;

/**
 *
 * @author  Luc Vannier
 */
public class JFrGothaStart extends javax.swing.JFrame {

	private GothaLocale locale;

    /** Creates new form JFrGothaStart */
    public JFrGothaStart() {
		this.locale = GothaLocale.getCurrentLocale();

        // Log Platform and JDK elements
        
        String strOS = System.getProperty("os.name") + " " + System.getProperty("os.arch") + " " + System.getProperty("os.version");
        LogElements.incrementElement("gotha.os", strOS);
        String strJRE = System.getProperty("java.version") + " " + System.getProperty("java.vm.name");
        LogElements.incrementElement("gotha.jre", strJRE);
        String strVersion = Gotha.getGothaFullVersionNumber();
        LogElements.incrementElement("gotha.version", strVersion);

        File rootDir = new File(System.getProperty("user.dir"));
        File dir = findADirectoryContaining(rootDir, "tournamentfiles");

        if (dir == null) {
            String str = JOptionPane.showInputDialog(this, locale.getString("start.input_workdir"),
                    rootDir.toString());
            if (!new File(str, "tournamentfiles").exists())
                JOptionPane.showMessageDialog(this, locale.getString("start.input_workdir_error"), locale.getString("alert.message"),
                        JOptionPane.WARNING_MESSAGE);
            dir = new File(str);
        }

        Gotha.runningDirectory = dir;
        Gotha.exportDirectory = new File(Gotha.runningDirectory, "exportfiles");
        Gotha.exportHTMLDirectory = new File(Gotha.runningDirectory, "exportfiles/html");
        initComponents();
        customInitComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpLanguage = new javax.swing.ButtonGroup();
        grpRunningMode = new javax.swing.ButtonGroup();
        btnStart = new javax.swing.JButton();
        pnlRunningMode = new javax.swing.JPanel();
        rdbSAL = new javax.swing.JRadioButton();
        rdbServer = new javax.swing.JRadioButton();
        rdbClient = new javax.swing.JRadioButton();
        btnHelp = new javax.swing.JButton();
        pnlLocale = new javax.swing.JPanel();
        languageComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new MigLayout("flowy", ":push[fill, sgx column, 170lp]20lp[fill, sgx column]:push", "[grow 100][grow 0]unrel:push[grow 0]rel[grow 0][grow 100]"));

        pnlRunningMode.setBorder(javax.swing.BorderFactory.createTitledBorder(locale.getString("start.mode"))); // NOI18N
        pnlRunningMode.setLayout(new MigLayout("gap 15lp, ins 10lp, flowy"));

        grpRunningMode.add(rdbSAL);
        rdbSAL.setSelected(true);
        pnlRunningMode.add(rdbSAL);

        grpRunningMode.add(rdbServer);
        pnlRunningMode.add(rdbServer);

        grpRunningMode.add(rdbClient);
        pnlRunningMode.add(rdbClient);

        getContentPane().add(pnlRunningMode, "skip, spany 3, wrap");

        pnlLocale.setBorder(javax.swing.BorderFactory.createTitledBorder(locale.getString("start.language"))); // NOI18N
        pnlLocale.setLayout(new MigLayout("ins 10lp"));

        languageComboBox.setModel(ru.gofederation.gotha.util.GothaLocale.getCurrentLocale());
        languageComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                languageComboBoxActionPerformed(evt);
            }
        });
        pnlLocale.add(languageComboBox, "w 120lp");

        getContentPane().add(pnlLocale, "skip");

        btnHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/info/vannier/gotha/gothalogo16.jpg"))); // NOI18N
        btnHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpActionPerformed(evt);
            }
        });
        getContentPane().add(btnHelp, "sg buttons");

        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });
        getContentPane().add(btnStart, "sg buttons");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void customInitComponents() {
        int w = JFrGotha.SMALL_FRAME_WIDTH;
        int h = JFrGotha.SMALL_FRAME_HEIGHT;
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((dim.width - w) / 2, (dim.height - h) / 2, w, h);

        setIconImage(Gotha.getIconImage());

		updateLocale();
    }

	private void updateLocale() {
		locale = GothaLocale.getCurrentLocale();
		Gotha.locale = locale.getLocale();

		setTitle(locale.getString("start.window_title"));
		btnStart.setText(locale.getString("start.btn_start"));
		pnlRunningMode.setBorder(javax.swing.BorderFactory.createTitledBorder(locale.getString("start.mode")));
		rdbSAL.setText(locale.getString("start.standalone"));
		rdbServer.setText(locale.getString("start.server"));
		rdbClient.setText(locale.getString("start.client"));
		rdbClient.setToolTipText(locale.getString("start.client.tooltip"));
		btnHelp.setText(locale.getString("btn.help"));
		pnlLocale.setBorder(javax.swing.BorderFactory.createTitledBorder(locale.getString("start.language")));
	}

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        Gotha.locale = new Locale("en");

        Gotha.runningMode = Gotha.RUNNING_MODE_UNDEFINED;

        TournamentInterface tournament = null;

        if (grpRunningMode.getSelection() == this.rdbSAL.getModel()) {
            Gotha.runningMode = Gotha.RUNNING_MODE_SAL;
        }

        if (grpRunningMode.getSelection() == this.rdbServer.getModel()) {

            String strIPAd = Gotha.getBestIPAd().toString();
            strIPAd = strIPAd.replace("/", "");
            strIPAd = JOptionPane.showInputDialog(locale.getString("start.input_this_server_ip"), strIPAd);
            if (strIPAd == null) return;

            System.setProperty("java.rmi.server.hostname", strIPAd);

            Gotha.runningMode = Gotha.RUNNING_MODE_SRV;
        }

        if (grpRunningMode.getSelection() == this.rdbClient.getModel()) {
            String strSN = "";
            try {
                strSN = InetAddress.getLocalHost().getHostAddress();
            } catch (java.net.UnknownHostException ex) {
                            Logger.getLogger(JFrGothaStart.class.getName()).log(Level.SEVERE, null, ex);
            }
            Gotha.serverName = JOptionPane.showInputDialog(locale.getString("start.input_server_address"), strSN);

            String[] lstTou = GothaRMIClient.tournamentNamesList(Gotha.serverName);
            String strTN = "";
            if (lstTou == null || lstTou.length == 0){
                String strMessage = locale.format("start.no_tournaments_found_on_server", strSN);
                JOptionPane.showMessageDialog(this, strMessage);
                return;
            }
            if (lstTou.length > 0) {
                strTN = (String) JOptionPane.showInputDialog(this, locale.getString("start.select_tournament"), "OpenGotha",
                        JOptionPane.INFORMATION_MESSAGE, null, lstTou, lstTou[0]);
            }
            
            tournament = GothaRMIClient.getTournament(Gotha.serverName, strTN);
            try {
                Gotha.clientName = tournament.addGothaRMIClient(Gotha.getHostName());
            } catch (RemoteException ex) {
                Logger.getLogger(JFrGothaStart.class.getName()).log(Level.SEVERE, null, ex);
            }
            Gotha.runningMode = Gotha.RUNNING_MODE_CLI;
        }
        
        // Log elements
        String strRM = "";
        switch(Gotha.runningMode){
            case Gotha.RUNNING_MODE_SAL : strRM = "SAL"; break;
            case Gotha.RUNNING_MODE_SRV : strRM = "SRV"; break;
            case Gotha.RUNNING_MODE_CLI : strRM = "CLI"; break;
            default : strRM = "???"; 
        }       
        LogElements.incrementElement("gotha.runningmode", strRM);

        try {
            new JFrGotha(tournament).setVisible(true);
        } catch (RemoteException ex) {
            Logger.getLogger(JFrGothaStart.class.getName()).log(Level.SEVERE, null, ex);
        }

        dispose();
    }//GEN-LAST:event_btnStartActionPerformed

    private void btnHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpActionPerformed
        Gotha.displayGothaHelp("Starting OpenGotha");
    }//GEN-LAST:event_btnHelpActionPerformed

    private void languageComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_languageComboBoxActionPerformed
        updateLocale();
    }//GEN-LAST:event_languageComboBoxActionPerformed

    /**
     * Recursively searches for a directory containing a directory whose name is strFile
     * @param rootDir
     * @param strFile
     * @return
     */
    public File findADirectoryContaining(File rootDir, String strFile){
        if (new File(rootDir, strFile).exists()){
            return rootDir;
        }
        else{
            File[] lst = rootDir.listFiles();
            if (lst == null) return null;
            for (int i = 0; i < lst.length; i++){
                if (!lst[i].isDirectory()) continue;
                if (lst[i].isHidden()) continue;
                File f = findADirectoryContaining(lst[i], strFile);
                if (f!= null){
                    return f;
                }
            }
            return null;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new JFrGothaStart().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHelp;
    private javax.swing.JButton btnStart;
    private javax.swing.ButtonGroup grpLanguage;
    private javax.swing.ButtonGroup grpRunningMode;
    private javax.swing.JComboBox<ru.gofederation.gotha.util.GothaLocale> languageComboBox;
    private javax.swing.JPanel pnlLocale;
    private javax.swing.JPanel pnlRunningMode;
    private javax.swing.JRadioButton rdbClient;
    private javax.swing.JRadioButton rdbSAL;
    private javax.swing.JRadioButton rdbServer;
    // End of variables declaration//GEN-END:variables
}
